# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designs/design_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CurrencyWindow(object):
    def setupUi(self, CurrencyWindow):
        CurrencyWindow.setObjectName("CurrencyWindow")
        CurrencyWindow.resize(300, 600)
        self.centralwidget = QtWidgets.QWidget(CurrencyWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Magistral Book")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.currency_search = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.currency_search.setEnabled(True)
        self.currency_search.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily("Magistral Book")
        self.currency_search.setFont(font)
        self.currency_search.setPlainText("")
        self.currency_search.setObjectName("currency_search")
        self.verticalLayout.addWidget(self.currency_search)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 278, 399))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_cancel = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Magistral Book")
        self.button_cancel.setFont(font)
        self.button_cancel.setStyleSheet("background-color: rgb(255, 159, 69);")
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout.addWidget(self.button_cancel)
        self.button_admit = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Magistral Book")
        self.button_admit.setFont(font)
        self.button_admit.setStyleSheet("background-color: rgb(255, 159, 69);")
        self.button_admit.setObjectName("button_admit")
        self.horizontalLayout.addWidget(self.button_admit)
        self.verticalLayout.addWidget(self.frame)
        CurrencyWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(CurrencyWindow)
        self.statusbar.setObjectName("statusbar")
        CurrencyWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CurrencyWindow)
        QtCore.QMetaObject.connectSlotsByName(CurrencyWindow)

    def retranslateUi(self, CurrencyWindow):
        _translate = QtCore.QCoreApplication.translate
        CurrencyWindow.setWindowTitle(_translate("CurrencyWindow", "Settings"))
        self.label.setText(_translate("CurrencyWindow", "Выберите валюты, курсы которых Вы хотите видеть на главном экране"))
        self.button_cancel.setText(_translate("CurrencyWindow", "Отмена"))
        self.button_admit.setText(_translate("CurrencyWindow", "Подтвердить"))
