# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 507)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("background-color: rgb(255, 188, 128);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.top_bar.setStyleSheet("background-color: rgb(255, 159, 69);")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.top_bar)
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 40))
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_toggle)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_toggle = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle.sizePolicy().hasHeightForWidth())
        self.btn_toggle.setSizePolicy(sizePolicy)
        self.btn_toggle.setStyleSheet("border: 0px;")
        self.btn_toggle.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("designs/menu.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_toggle.setIcon(icon)
        self.btn_toggle.setIconSize(QtCore.QSize(32, 32))
        self.btn_toggle.setObjectName("btn_toggle")
        self.horizontalLayout_3.addWidget(self.btn_toggle)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.top_bar)
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(255, 159, 69);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_menu_2 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_menu_2.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_menu_2.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px;\n"
"    margin: 5px 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(250, 151, 52);\n"
"    transition: 0.2s;\n"
"}")
        self.btn_menu_2.setObjectName("btn_menu_2")
        self.verticalLayout_3.addWidget(self.btn_menu_2)
        self.btn_menu_3 = QtWidgets.QPushButton(self.frame_top_menus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_menu_3.sizePolicy().hasHeightForWidth())
        self.btn_menu_3.setSizePolicy(sizePolicy)
        self.btn_menu_3.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_menu_3.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px;\n"
"    margin: 5px 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(250, 151, 52);\n"
"    transition: 0.2s;\n"
"}")
        self.btn_menu_3.setObjectName("btn_menu_3")
        self.verticalLayout_3.addWidget(self.btn_menu_3)
        self.btn_menu_4 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_menu_4.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_menu_4.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px;\n"
"    margin: 5px 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(250, 151, 52);\n"
"    transition: 0.2s;\n"
"}")
        self.btn_menu_4.setObjectName("btn_menu_4")
        self.verticalLayout_3.addWidget(self.btn_menu_4)
        self.btn_menu_1 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_menu_1.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_menu_1.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px;\n"
"    margin: 5px 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(250, 151, 52);\n"
"    transition: 0.2s;\n"
"}")
        self.btn_menu_1.setObjectName("btn_menu_1")
        self.verticalLayout_3.addWidget(self.btn_menu_1)
        self.verticalLayout_2.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.content)
        self.frame_pages.setStyleSheet("")
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pages_widget = QtWidgets.QStackedWidget(self.frame_pages)
        self.pages_widget.setObjectName("pages_widget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pages_widget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.pages_widget.addWidget(self.page_2)
        self.verticalLayout_4.addWidget(self.pages_widget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.content)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_menu_2.setText(_translate("MainWindow", "Menu 1"))
        self.btn_menu_3.setText(_translate("MainWindow", "Menu 2"))
        self.btn_menu_4.setText(_translate("MainWindow", "Menu 3"))
        self.btn_menu_1.setText(_translate("MainWindow", "Menu 4"))
